# swarm-code — terminal coding agent built in sw on the swarmrt runtime

SWARMRT ?= ../swarmrt
SWC     := $(SWARMRT)/bin/swc

SRC_DIR := src
BIN     := bin/swarm-code

# All .sw files — let make rebuild on any change. Easier than
# maintaining this list by hand every time we add a module.
SOURCES := $(wildcard $(SRC_DIR)/*.sw)

# Version comes from the VERSION file at the repo root (single line,
# e.g. 0.4.0) — not `git describe`, so tarball builds without .git and
# pre-tag branches still report the right version. Release tags in
# .github/workflows/release.yml should match VERSION.
VERSION_STR := $(shell cat VERSION 2>/dev/null || echo 0.0.0-dev)

TESTBIN := bin/swarm-code-test

.PHONY: all clean run test smoke integration module-check test-all check run-local FORCE

all: $(BIN)

# src/Version.sw is generated from VERSION on every build (FORCE), but
# only rewritten when the content actually changes — an unchanged
# VERSION never bumps the mtime, so it never dirties rebuilds.
FORCE:
$(SRC_DIR)/Version.sw: VERSION FORCE
	@printf 'module Version\n\n# AUTO-GENERATED by make from the VERSION file at the repo root — do not edit.\nfun version() { "%s" }\n' "$(VERSION_STR)" > $@.tmp; \
	if cmp -s $@.tmp $@; then rm $@.tmp; else mv $@.tmp $@; fi

$(BIN): $(SRC_DIR)/Version.sw $(SOURCES)
	@mkdir -p bin
	$(SWC) build $(SRC_DIR)/main.sw -o $(BIN)
	@echo "swarm-code: built $(BIN)"

# Test suite — builds and runs bin/swarm-code-test. Exits non-zero
# if any check fails, so `make test` works in CI / pre-commit.
test: $(TESTBIN)
	@./$(TESTBIN)

$(TESTBIN): $(SRC_DIR)/Version.sw $(SOURCES)
	@mkdir -p bin
	@$(SWC) build $(SRC_DIR)/test_runner.sw -o $(TESTBIN)

clean:
	rm -rf bin

run: $(BIN)
	./$(BIN)

# Smoke test — boots the binary in headless mode, runs one bash tool call,
# verifies the response. Used by tests/smoke.sh.
smoke: $(BIN)
	@SWARM_CODE_NO_RESUME=1 BIN=./$(BIN) ./tests/smoke.sh

# Integration (E2E) suite — runs the real binary headless against a
# scripted mock LLM endpoint (tests/integration/). Isolated $HOME per
# test; needs only python3 + curl. See tests/integration/run.sh.
integration: $(BIN)
	@BIN=./$(BIN) ./tests/integration/run.sh

# Compile and run the focused per-module checks in tests/. The main
# regression suite runs via `make test`.
module-check:
	@./tests/run_all.sh

# Backwards-compatible alias used by older contributor docs/scripts.
test-all: module-check

# Production gate: one command for local verification, CI, and releases.
check: test smoke integration module-check

# Handy one-liner for ad hoc testing against a local endpoint.
run-local: $(BIN)
	SWARM_CODE_ENDPOINT=http://localhost:8000 ./$(BIN)
