module Arthopod

# ============================================================
# Arthopod — the buddy companion for swarm-code
# ============================================================
#
# Inspired by Claude Code's "buddy" system (tamagotchi-style companion
# with deterministic bones + model-generated soul) but insect-themed.
#
# Deterministic bones are derived from hash($USER) so the same user
# always gets the same species/rarity/eye/hat/stats. The soul (name
# and personality) is generated by the LLM on first hatch and stored
# at ~/.swarm-code/arthopod.json so it persists across runs.
#
# Rendering is ASCII-art sprite + optional speech bubble. Speech
# bubbles fire on session start, after every Nth turn, and whenever
# the user addresses the buddy by name.

import LLM

export [
    hatch, render, render_with_bubble,
    greet_line, farewell_line, rare_wisdom_line,
    is_addressed, address_response,
    species_list
]

# ------------------------------------------------------------
# Species and rarity
# ------------------------------------------------------------
fun species_list() {
    [
        "beetle", "ant", "mantis", "bee", "firefly",
        "dragonfly", "ladybug", "cricket", "moth", "spider"
    ]
}

fun rarity_weights() {
    # Reflects CC's weights: common 60, uncommon 25, rare 10, epic 4, legendary 1
    [
        {"common",     60},
        {"uncommon",   25},
        {"rare",       10},
        {"epic",        4},
        {"legendary",   1}
    ]
}

fun rarity_stars(r) {
    if (r == "common")    { "★" }
    else { if (r == "uncommon")  { "★★" }
    else { if (r == "rare")      { "★★★" }
    else { if (r == "epic")      { "★★★★" }
    else { if (r == "legendary") { "★★★★★" }
    else { "★" }}}}}
}

fun rarity_color(r) {
    if (r == "common")    { "\e[38;5;244m" }        # grey
    else { if (r == "uncommon")  { "\e[38;5;78m"  }  # green
    else { if (r == "rare")      { "\e[38;5;75m"  }  # blue
    else { if (r == "epic")      { "\e[38;5;141m" }  # purple
    else { if (r == "legendary") { "\e[38;5;220m" }  # gold
    else { "\e[38;5;244m" }}}}}
}

# ------------------------------------------------------------
# Deterministic bones from a seed string
# ------------------------------------------------------------
# We shell out to `shasum` to get a hex digest of the seed (user name),
# then use bytes of that hex string to index into species/rarity/etc.

fun bones_from_seed(seed) {
    hex_cmd = "printf '%s' '" ++ shell_escape(seed) ++ "' | shasum -a 256 | cut -c1-16"
    result = shell(hex_cmd)
    hex = string_trim(elem(result, 1))

    # Derive indices from hex characters (each is 0-15).
    sp_raw = hex_byte(hex, 0)
    sp_list = species_list()
    species_idx = sp_raw - sp_raw / length(sp_list) * length(sp_list)

    rr_hi = hex_byte(hex, 2)
    rr_lo = hex_byte(hex, 3)
    rarity_roll = rr_hi * 16 + rr_lo

    ey_raw = hex_byte(hex, 4)
    eye_idx = ey_raw - ey_raw / 6 * 6

    ht_raw = hex_byte(hex, 5)
    hat_idx = ht_raw - ht_raw / 8 * 8

    shiny_roll = hex_byte(hex, 6)

    species = list_nth(sp_list, species_idx)
    rarity_mod = rarity_roll - rarity_roll / 100 * 100
    rarity = pick_rarity_by_weight(rarity_mod)
    eye = list_nth(["·", "•", "✦", "◉", "o", "@"], eye_idx)
    hat = list_nth(
        ["none", "crown", "tophat", "propeller", "halo", "wizard", "beanie", "antenna"],
        hat_idx)
    shiny = if (shiny_roll == 0) { 'true' } else { 'false' }

    %{
        species: species,
        rarity: rarity,
        eye: eye,
        hat: hat,
        shiny: shiny
    }
}

fun shell_escape(s) {
    # Strip single quotes and newlines; crude but sufficient for $USER.
    no_quotes = string_replace(s, "'", "")
    string_replace(no_quotes, "\n", "")
}

# Parse a single hex digit at index i into 0..15.
fun hex_byte(hex, i) {
    c = string_sub(hex, i, 1)
    if (c == "0") { 0 } else {
    if (c == "1") { 1 } else {
    if (c == "2") { 2 } else {
    if (c == "3") { 3 } else {
    if (c == "4") { 4 } else {
    if (c == "5") { 5 } else {
    if (c == "6") { 6 } else {
    if (c == "7") { 7 } else {
    if (c == "8") { 8 } else {
    if (c == "9") { 9 } else {
    if (c == "a") { 10 } else {
    if (c == "b") { 11 } else {
    if (c == "c") { 12 } else {
    if (c == "d") { 13 } else {
    if (c == "e") { 14 } else {
    if (c == "f") { 15 } else { 0 }}}}}}}}}}}}}}}}
}

fun list_nth(lst, i) {
    if (i <= 0) { hd(lst) }
    else {
        if (length(lst) == 1) { hd(lst) }
        else { list_nth(tl(lst), i - 1) }
    }
}

fun pick_rarity_by_weight(n) {
    # n is 0..99. Common 0..59, uncommon 60..84, rare 85..94, epic 95..98, legendary 99.
    if (n < 60) { "common" }
    else { if (n < 85) { "uncommon" }
    else { if (n < 95) { "rare" }
    else { if (n < 99) { "epic" }
    else { "legendary" }}}}
}

# ------------------------------------------------------------
# Hatch — load or generate soul, combine with bones
# ------------------------------------------------------------
fun hatch(opts) {
    seed = getenv("USER")
    effective_seed = if (seed == nil) { "anonymous" } else { seed }
    bones = bones_from_seed(effective_seed)

    soul_path = getenv("HOME") ++ "/.swarm-code/arthopod.json"
    soul = if (file_exists(soul_path) == 'true') {
        content = file_read(soul_path)
        if (content == nil) { generate_soul(bones, soul_path, opts) }
        else {
            decoded = json_decode(content)
            if (decoded == nil) { generate_soul(bones, soul_path, opts) }
            else { decoded }
        }
    } else {
        generate_soul(bones, soul_path, opts)
    }

    map_merge(bones, soul)
}

fun generate_soul(bones, soul_path, opts) {
    species = map_get(bones, 'species')
    rarity = map_get(bones, 'rarity')
    prompt = "Invent a short name (1-2 words) and a one-sentence personality " ++
             "for a small " ++ rarity ++ " " ++ species ++ " companion that " ++
             "sits beside a terminal coding agent and occasionally comments. " ++
             "Reply EXACTLY in this JSON format with no other text:\n" ++
             "{\"name\":\"...\",\"personality\":\"...\"}"
    msgs = [
        {'system', "You are a creative naming assistant. Reply with ONLY a JSON object."},
        {'user', prompt}
    ]
    response = LLM.chat(msgs, opts)
    parsed = if (response == nil) { nil } else { extract_soul_json(response) }

    final_soul = if (parsed == nil) {
        %{name: "Zippy", personality: "Friendly and curious."}
    } else { parsed }

    # Persist.
    file_mkdir(getenv("HOME") ++ "/.swarm-code")
    file_write(soul_path, json_encode(final_soul))
    final_soul
}

# Extract the first JSON object from a potentially chatty response.
fun extract_soul_json(text) {
    # Look for a { ... } block; crude but effective.
    start_marker = "\x01SOULSTART\x01"
    end_marker = "\x01SOULEND\x01"
    # Can't do direct substring search without more builtins — pass it through
    # json_decode directly; if it fails, return nil.
    cleaned = string_trim(text)
    decoded = json_decode(cleaned)
    if (decoded == nil) {
        # Try stripping code fences.
        stripped = strip_code_fences(cleaned)
        json_decode(stripped)
    } else {
        decoded
    }
}

fun strip_code_fences(s) {
    # Remove ```json and ``` markers.
    no_start = string_replace(s, "```json", "")
    no_middle = string_replace(no_start, "```", "")
    string_trim(no_middle)
}

# ------------------------------------------------------------
# Sprite — ASCII art per species (3 lines each for compactness)
# ------------------------------------------------------------
fun sprite(species, eye) {
    if (species == "beetle") {
        [" ,-==-,",
         "(" ++ eye ++ " | " ++ eye ++ ")",
         " '----'"]
    }
    else { if (species == "ant") {
        [" o",
         "/|\\",
         "<" ++ eye ++ ">"]
    }
    else { if (species == "mantis") {
        ["  \\_/",
         " (" ++ eye ++ " " ++ eye ++ ")",
         " <| |>"]
    }
    else { if (species == "bee") {
        [" ,'\"'.",
         "(" ++ eye ++ "≡" ++ eye ++ ")",
         " `~Y~'"]
    }
    else { if (species == "firefly") {
        ["  .*.",
         " (" ++ eye ++ "_" ++ eye ++ ")",
         "  *~*"]
    }
    else { if (species == "dragonfly") {
        ["=<" ++ eye ++ ">=",
         "  |  ",
         " /|\\ "]
    }
    else { if (species == "ladybug") {
        [" .---.",
         "(" ++ eye ++ "•" ++ eye ++ ")",
         " `---'"]
    }
    else { if (species == "cricket") {
        [" /\\/\\",
         "(" ++ eye ++ " " ++ eye ++ ")",
         " ^^^^"]
    }
    else { if (species == "moth") {
        [" ><" ++ eye ++ "><",
         " <|||>",
         "  `v'"]
    }
    else { if (species == "spider") {
        [" /|_|\\",
         "(" ++ eye ++ "_" ++ eye ++ ")",
         " /|_|\\"]
    }
    else {
        ["  .",
         " (" ++ eye ++ ")",
         "  ^"]
    }}}}}}}}}}
}

# Hat decoration (single line printed above the sprite).
fun hat_line(hat) {
    if (hat == "crown")     { "  ♔  " }
    else { if (hat == "tophat")    { "  ▯  " }
    else { if (hat == "propeller") { "  ✈  " }
    else { if (hat == "halo")      { "  ○  " }
    else { if (hat == "wizard")    { "  ▲  " }
    else { if (hat == "beanie")    { "  ⌒  " }
    else { if (hat == "antenna")   { " Y Y " }
    else { "     " }}}}}}}
}

# ------------------------------------------------------------
# Render — print sprite (+ optional bubble)
# ------------------------------------------------------------
fun render(buddy) {
    species = map_get(buddy, 'species')
    eye = map_get(buddy, 'eye')
    hat = map_get(buddy, 'hat')
    rarity = map_get(buddy, 'rarity')
    name = map_get(buddy, 'name')
    col = rarity_color(rarity)

    lines = sprite(species, eye)
    hat_str = hat_line(hat)
    shiny = map_get(buddy, 'shiny')
    sparkle = if (shiny == 'true') { " ✨" } else { "" }

    print("")
    print("  " ++ col ++ hat_str ++ "\e[0m")
    print("  " ++ col ++ hd(lines) ++ "\e[0m")
    print("  " ++ col ++ hd(tl(lines)) ++ "\e[0m  \e[1m" ++ to_string(name) ++ "\e[0m" ++ sparkle)
    print("  " ++ col ++ hd(tl(tl(lines))) ++ "\e[0m  \e[2m" ++ rarity_stars(rarity) ++ " " ++ to_string(rarity) ++ " " ++ to_string(species) ++ "\e[0m")
}

# Render sprite with a speech bubble to the right of it.
fun render_with_bubble(buddy, text) {
    species = map_get(buddy, 'species')
    eye = map_get(buddy, 'eye')
    name = map_get(buddy, 'name')
    rarity = map_get(buddy, 'rarity')
    col = rarity_color(rarity)

    lines = sprite(species, eye)
    wrapped = wrap_text(text, 42)

    print("")
    # Speech bubble box.
    print("  " ++ col ++ hd(lines) ++ "\e[0m  \e[2m╭" ++ dashes(string_length(wrapped) + 2) ++ "╮\e[0m")
    print("  " ++ col ++ hd(tl(lines)) ++ "\e[0m  \e[2m│ \e[0m" ++ wrapped ++ "\e[2m │\e[0m")
    print("  " ++ col ++ hd(tl(tl(lines))) ++ "\e[0m  \e[2m╰" ++ dashes(string_length(wrapped) + 2) ++ "╯\e[0m")
    print("     \e[2m— " ++ to_string(name) ++ "\e[0m")
}

fun wrap_text(s, max_len) {
    # For v1, just truncate to max_len. Real wrapping across lines later.
    if (string_length(s) <= max_len) {
        s
    } else {
        string_sub(s, 0, max_len - 2) ++ ".."
    }
}

fun dashes(n) {
    if (n <= 0) { "" }
    else {
        if (n == 1) { "─" }
        else { "─" ++ dashes(n - 1) }
    }
}

# ------------------------------------------------------------
# Pre-canned one-liners (no LLM call needed for these)
# ------------------------------------------------------------
fun greet_line(buddy) {
    species = map_get(buddy, 'species')
    rarity = map_get(buddy, 'rarity')
    name = map_get(buddy, 'name')
    "Hi, I'm " ++ to_string(name) ++ " — a " ++ to_string(rarity) ++
        " " ++ to_string(species) ++ ". I'll be here while you code."
}

fun farewell_line(buddy) {
    name = map_get(buddy, 'name')
    "See you next session. — " ++ to_string(name)
}

fun rare_wisdom_line(buddy) {
    name = map_get(buddy, 'name')
    rarity = map_get(buddy, 'rarity')
    if (rarity == "legendary") {
        "(I could show you things no common beetle has ever seen, friend.)"
    } else {
        "(keep going — " ++ to_string(name) ++ " is watching quietly)"
    }
}

# ------------------------------------------------------------
# Address detection & LLM-backed responses
# ------------------------------------------------------------
fun is_addressed(text, buddy) {
    name = to_string(map_get(buddy, 'name'))
    lower = string_lower(text)
    name_lower = string_lower(name)
    if (string_contains(lower, name_lower) == 'true') { 'true' }
    else {
        if (string_contains(lower, "arthopod") == 'true') { 'true' }
        else { 'false' }
    }
}

fun address_response(buddy, user_text, opts) {
    species = to_string(map_get(buddy, 'species'))
    rarity = to_string(map_get(buddy, 'rarity'))
    name = to_string(map_get(buddy, 'name'))
    personality = to_string(map_get(buddy, 'personality'))

    system = "You are " ++ name ++ ", a small " ++ rarity ++ " " ++ species ++
        " companion sitting beside a terminal coding agent. " ++
        "Personality: " ++ personality ++ ". " ++
        "The user is addressing you directly. Respond in ONE short line (max " ++
        "20 words). Stay in character. Do not narrate — just speak."
    msgs = [
        {'system', system},
        {'user', user_text}
    ]
    response = LLM.chat(msgs, opts)
    if (response == nil) {
        "*chirps quietly*"
    } else {
        string_trim(response)
    }
}
